### ISSUE TITLE
multi-line strings (and their literals) in an array are not formatted correctly

### ISSUE THREAD

**Issue by nokazn** [dprint/dprint-plugin-toml#10]
**Describe the bug**

dprint-plugin-toml version: 0.5.4

I think white spaces in [multi-line string and multi-line literal string](https://github.com/toml-lang/toml/blob/main/toml.md#string) should keep as they are, even when these strings are in an array.
Currently some indents are inserted in multi-line (literal) strings contents, and `dprint fmt` tells the below error.

```sh
Error formatting /home/nokazn/externals/dprint-plugin-toml/example.toml. Message: Formatting not stable. Bailed after 5 tries. This indicates a bug in the plugin where it formats the file differently each time.
Had 1 error(s) formatting.
```

**Input Code**

```toml
strings = [
  """
  This is
  a
  multi-line
  string
  """,
            '''This is
    a multi-line literal string


        ''',
]

```

**Expected Output**

```toml
strings = [
  """
  This is
  a
  multi-line
  string
  """,
  '''This is
    a multi-line literal string


        ''',
]

```

**Actual Output**

```toml
strings = [
  """
    This is
    a
    multi-line
    string
    """,
  '''This is
      a multi-line literal string


          ''',
]

```

**Comment by dsherret** [comment]
Thanks for reporting! It should be fixed in 0.6.0
