### ISSUE TITLE
Formatting files written in Taplo's schema directive inserts unwanted spaces

### ISSUE THREAD

**Issue by wancup** [dprint/dprint-plugin-toml#14]
version: toml-0.6.1.wasm

When formatting files using Taplo's `schema Directive` (https://taplo.tamasfe.dev/configuration/directives.html#the-schema-directive), a space is inserted between `#` and `:`, causing Taplo's language server to no longer recognize it as a directive.

```toml
#:schema https://json.schemastore.org/fly.json
```
↓
```toml
# :schema https://json.schemastore.org/fly.json
```

Is it possible to avoid this behavior, for example by disabling formatting for the next line with a comment like `# dprint-ignore`, or through some configuration?

**Comment by wancup** [comment]
Oh, sorry!
By setting `comment.forceLeadingSpace` to `false` in the configuration, I was able to avoid this!

**Comment by b0o** [comment]
> I would if dprint should leave these kind of comments alone.

I think it should leave them alone. It's silly to need to configure it on each project that uses json schema directives.
