### ISSUE TITLE
dprint is complaining about the order of the edition parameter on Cargo.toml

### ISSUE THREAD

**Issue by eduardonunesp** [dprint/dprint-plugin-toml#6]
Version: 0.27.0

I think this error started to happening after the updates on packages with the latest version of Rust edition, not sure why but dprint now is complaining about the position of the `edition` parameter, if the parameter edition is moved to last position on the list the command `dprint`  going to work ok

```
target/release/wbuild/polkadot-runtime/Cargo.toml:
 9  9| name·=·'polkadot_runtime'
10 10| 
11 11| [package]
   12|-edition·=·'2021'
12 13| name·=·'polkadot-runtime-wasm'
13 14| version·=·'1.0.0'
14   |+edition·=·'2021'
15 15| [profile.dev]
16 16| panic·=·'abort'
```

**Comment by dsherret** [comment]
dprint-plugin-toml formats Cargo.toml files according to https://github.com/rust-lang/rfcs/blob/master/style-guide/cargo.md -- which will put name and version keys at the top.

You can disable it by specifying `"cargo.applyConventions": false` in your dprint.json file.

Sorry, the documentation is non-existent at the moment. I opened https://github.com/dprint/dprint-plugin-toml/issues/7 to improve this

**Comment by eduardonunesp** [comment]
That's ok, thanks @dsherret for the answer
